version: '3'

services:

  db:
    image: postgres:14.1-alpine
    platform: linux/x86_64
    container_name: indigolabs_test.db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - bot-network

  php:
    container_name: indigolabs_test.php
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        TIMEZONE: Europe/Moscow
    volumes:
      - ../:/var/www/indigolabs-test
    restart: unless-stopped
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
      PHP_IDE_CONFIG: "serverName=Docker"
    working_dir: /var/www/indigolabs-test
    networks:
      - bot-network

  nginx:
    container_name: indigolabs_test.nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ../:/var/www/indigolabs-test
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    restart: unless-stopped
    tty: true
    ports:
      - "8088:80"
    networks:
      - bot-network
    extra_hosts:
      - "host.docker.internal:127.0.0.1"

volumes:
  db:
    driver: local

networks:
  bot-network:
    driver: bridge
